### PR TITLE
fix for compilation with ssl on windows

### PR DESCRIPTION
**Pull request by krzcho**
it was proposed to main EM but it is sleeping there, wanna try with LE

### CODE REVIEW

**Comment by krzcho** [comment]
hmm it manages to see ssl libs now but won't compile:
ed.cpp: In member function 'void ConnectionDescriptor::_DispatchInboundData(const char*, int)':
ed.cpp:844:23: error: 'EPROTO' was not declared in this scope
any hint for that?

**Comment by krzcho** [comment]
linux system error codes
http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html
...

**Comment by krzcho** [comment]
ok, i confirm it builds fine on windows now
here i got exactly the same problem with certificates as with normal eventmachine :(
http://stackoverflow.com/questions/31059658/thin-rails-server-on-windows-does-not-work-with-custom-certificate

**Comment by krzcho** [comment]
this comment in ssl.cpp says it all

	/* TODO: the usage of the specified private-key and cert-chain filenames only applies to
	 * client-side connections at this point. Server connections currently use the default materials.
	 * That needs to be fixed asap.
	 * Also, in this implementation, server-side connections use statically defined X-509 defaults.
	 * One thing I'm really not clear on is whether or not you have to explicitly free X509 and EVP_PKEY
	 * objects when we call our destructor, or whether just calling SSL_CTX_free is enough.
	 */

**Comment by ibc** [comment]
Hi @krzcho, may you please confirm that these changes do not break stuff in Linux/OSX?

**Comment by krzcho** [comment]
only theoretically (all changes are under OS_WIN32 directive) as I do not have linux available

**Comment by ibc** [comment]
It will take some time until I can check it, but I will do. Thanks.

**Comment by krzcho** [comment]
all modifications are aimed at windows, it was very easy task, see files changed

**Comment by sodabrew** [comment]
Please try upstream EventMachine 1.0.8 or higher, and EventMachine 1.2.0.dev.2, which incorporate similar fixes for Windows. Feedback appreciated as the upstream EventMachine 1.2.0 release substantially incorporates the work from EventMachine-LE 1.1.x.

**Comment by krzcho** [comment]
@sodabrew I am not totally sure about your intentions from the post above but if you were asking to confirm ssl working with EventMachine 1.2.0.dev.2 on windows then I do confirm it works fine (and it is working fine since 1.0.8)
(but maybe it was just about closing the issue which I have now closed as well)

**Pull request closed without merging**
